### ISSUE TITLE
dotenv à éviter

### ISSUE THREAD

**Issue by vavarm** [louis-marceron/web-project-api-template#3]
Dotenv va poser des problèmes avec les hébergeurs. Lorsqu'on aura besoin d'utiliser des variables d'environnement ce sera mieux d'utiliser un OU logique entre une variable d'environnement et une valeur par défaut.

**Comment by louis-marceron** [comment]
Quels problèmes ça risque de poser ? J'ai déjà mis des OU entre les variables d'environnement et les valeurs par défaut, mais comment tu comptes faire pour les identifiants de la BD ?

**Comment by louis-marceron** [comment]
Le dotenv est en dépendance de développement, le code peut maintenant être exécuté en production sans que l'absence de dotenv pose problème.
